### PR TITLE
Throw valid exceptions on service lookup and build

### LINKED ISSUE #151: Crash when registering null service
`builder.withService("lala", null);` should crash. It doesn't, and then the app crashes when trying to find the service, telling you it wasn't registered and confusing you.

If we want to allow masking services to children, we need `builder.maskService("lala");`.

### PR DESCRIPTION
**Pull request by vignesh-iopex**
`MortarScope#getService` to throw IllegalStateException if called after scope is destroyed
Null check before mapping service in a scope fixes #151
Add unit tests for MortarScope Builder

### CODE REVIEW

File: mortar/src/main/java/mortar/MortarScope.java [hunk 1]
```diff
@@ -95,14 +99,13 @@ public boolean hasService(String serviceName) {
 
   @SuppressWarnings("unchecked") //
   private <T> T findService(String serviceName) {
-    if (!isDestroyed()) {
-      if (SERVICE_NAME.equals(serviceName)) return (T) this;
+    assertNotDead();
```
Comment (rjrjr) [inline mortar/src/main/java/mortar/MortarScope.java]: I disagree with this change. getSystemService is too fundamental system for us to intrude on like this. I'd particularly expect it to cause problems during Activity teardown.

File: mortar/src/main/java/mortar/MortarScope.java [hunk 2]
```diff
@@ -195,11 +198,6 @@ void assertNotDead() {
      * method.
      */
     public Builder withService(String serviceName, Object service) {
-      if (service instanceof Scoped) {
```
Comment (rjrjr) [inline mortar/src/main/java/mortar/MortarScope.java]: Please don't remove this.

File: mortar/src/main/java/mortar/MortarScope.java (hunk 1 above)
Comment (vignesh-iopex) [inline mortar/src/main/java/mortar/MortarScope.java]: but currently it throws IllegalArgumentException because of the existing null check in getService

File: mortar/src/main/java/mortar/MortarScope.java (hunk 2 above)
Comment (vignesh-iopex) [inline mortar/src/main/java/mortar/MortarScope.java]: I will revert this deletion

File: mortar/src/main/java/mortar/MortarScope.java (hunk 1 above)
Comment (rjrjr) [inline mortar/src/main/java/mortar/MortarScope.java]: You're right, wasn't thinking.
